### PR TITLE
(MODULES-4287) Make rspec-puppet tests platform independent

### LINKED ISSUE #175: 'should compile' doesn't like 'groups' in 'user' definitions
I don't think 'should compile' supports 'groups' when defining users. Here's my init.pp:

```
class example () {
  user { 'example' :
    ensure  => present,
    uid     => 1234,
    gid     => 1234,
    groups  => 'localaccounts',
  }
}
```

Here's my init_spec.rb:

```
require 'spec_helper'

describe 'example' do
  context 'see if it compiles' do
    it { should compile }
  end
end
```

Here's the output of rspec -b:

```
F

Failures:

  1) example see if it compiles should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile }
     NoMethodError:
       undefined method `groups' for nil:NilClass
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/property/list.rb:57:in `retrieve'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/property/list.rb:46:in `should'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/type/user.rb:359:in `block (2 levels) in <module:Puppet>'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/type.rb:1995:in `instance_eval'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/type.rb:1995:in `block in autorequire'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/type.rb:1973:in `block in eachautorequire'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/type.rb:1972:in `each'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/type.rb:1972:in `eachautorequire'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/type.rb:1990:in `autorequire'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/graph/relationship_graph.rb:168:in `block in build_autorequire_dependencies'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/graph/relationship_graph.rb:167:in `each'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/graph/relationship_graph.rb:167:in `build_autorequire_dependencies'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/graph/relationship_graph.rb:25:in `populate_from'
     # /usr/local/lib/ruby/gems/2.0.0/gems/puppet-3.4.2/lib/puppet/resource/catalog.rb:189:in `relationship_graph'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/matchers/compile.rb:126:in `cycles_found?'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-puppet-1.0.1/lib/rspec-puppet/matchers/compile.rb:25:in `matches?'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-expectations-2.14.3/lib/rspec/expectations/handler.rb:24:in `handle_matcher'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/memoized_helpers.rb:68:in `should'
     # ./spec/classes/init_spec.rb:5:in `block (3 levels) in <top (required)>'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example.rb:114:in `instance_eval'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example.rb:114:in `block in run'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example.rb:111:in `run'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example_group.rb:390:in `block in run_examples'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example_group.rb:386:in `map'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example_group.rb:386:in `run_examples'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example_group.rb:371:in `run'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example_group.rb:372:in `block in run'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example_group.rb:372:in `map'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/example_group.rb:372:in `run'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/command_line.rb:28:in `map'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/command_line.rb:28:in `block in run'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/reporter.rb:58:in `report'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/command_line.rb:25:in `run'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/runner.rb:80:in `run'
     # /usr/local/lib/ruby/gems/2.0.0/gems/rspec-core-2.14.6/lib/rspec/core/runner.rb:17:in `block in autorun'

Finished in 0.53941 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/classes/init_spec.rb:5 # example see if it compiles should compile into a catalogue without dependency cycles
```

If I take out the 'groups' line, then it compiles just fine. Curiously, this test works just fine:

```
require 'spec_helper'

describe 'example' do
  context 'check the user' do
    it { should contain_user('example').with({
      'uid' => 1234,
      'gid' => 1234,
      'groups' => 'localaccounts',
    }) }
  end
end
```

I've tried this with the 1.0.1 gem, and also a download of the master ZIP at commit 03e94422fb9bbdd950d5a0bec6ead5d76e06616b - both have the problem. Any ideas?

### PR DESCRIPTION
**Pull request by rodjek**
In order to fully resolve the graph and create all the automatic relationships we have to convert the resource catalogue produced by the compiler into a RAL catalogue like that which an agent would apply.

An unfortunate side effect of this is that it causes providers to be loaded and tested for suitability. This can cause problems for people who have manifests that specify providers for platforms other than the one they're running rspec-puppet on (e.g. testing Windows manifests on a Linux host).

This PR adds a few monkey patches make this possible:

 * `Puppet::Type#set_default` has been modified so that we can prevent Puppet from assigning a default provider when performing catalogue tests (but not when testing the types themselves).
 * `Puppet::Util::Platform.windows?` has been modified so that can force Puppet to pretend that it's running on windows, allowing the windows specific parameter validations to succeed.
 * `Kernel.require` has been modified to prevent Puppet from requiring `puppet/util/windows` if Puppet is pretending to be running on windows in order to prevent it from requiring other libraries that generally aren't installed on non-windows hosts.
 * `Puppet::Node::Environment#validate_dirs` (if it exists, which it only does on Puppet < 3.x) has been wrapped to disable the windows pretending (if we're pretending) while the method is running as this is used by the compiler to determine if the paths on disk to the manifests is valid.

This PR supercedes #481

Closes #175 #192 #256 #352 #376 #387 #437

### CODE REVIEW

File: lib/rspec-puppet/monkey_patches.rb [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+    def self.suppress_provider
+      @suppress_provider = true
+    end
+
+    def self.unsuppress_provider
+      @suppress_provider = false
+    end
+  end
+
+  # If Puppet::Node::Environment has a validet_dirs instance method (i.e.
```
Comment (james-stocks) [inline lib/rspec-puppet/monkey_patches.rb]: Small typo on validet_dirs

File: lib/rspec-puppet/support.rb [hunk 2]
```diff
@@ -254,6 +254,19 @@ def build_catalog_without_cache(nodename, facts_val, trusted_facts_val, hiera_co
...
     def stub_facts!(facts)
+      if facts['operatingsystem'] && facts['operatingsystem'].to_s.downcase == 'windows'
+        # If we're not running in windows but are testing a catalogue destined
+        # for a windows host, pretend to be windows in the least awful way that
+        # I can think of.
+        unless Puppet::Util::Platform.windows?
+          Puppet::Util::Platform.pretend_windows
+          # On windows, puppet validates the value of the autosign setting as
+          # an absolute path unless it's disabled.
+          Puppet.settings[:autosign] = false
```
Comment (james-stocks) [inline lib/rspec-puppet/support.rb]: Is there a risk of breaking spec tests; if someone happened to be asserting this was true? I think if so; we could put somewhere in docs that we have this restriction when testing a module with Windows facts

File: lib/rspec-puppet/monkey_patches.rb (hunk 1 above)
Comment (rodjek) [inline lib/rspec-puppet/monkey_patches.rb]: Thanks, fixed :)

File: lib/rspec-puppet/support.rb (hunk 2 above)
Comment (rodjek) [inline lib/rspec-puppet/support.rb]: I don't think it's possible to break any specs by enforcing this value. It's a master setting and doesn't have any effect on the compilation of the catalogue.

File: lib/rspec-puppet/support.rb [hunk 3]
```diff
@@ -15,6 +15,27 @@ def environment
...
 
+    def stub_file_consts(example)
+      munged_facts = facts_hash(nodename(example.metadata[:type]))
+
+      if munged_facts['operatingsystem'] && munged_facts['operatingsystem'].to_s.downcase == 'windows'
+        stub_const_wrapper('PATH_SEPARATOR', ';')
+        stub_const_wrapper('ALT_SEPARATOR', "\\")
+      else
+        stub_const_wrapper('PATH_SEPARATOR', ':')
+        stub_const_wrapper('ALT_SEPARATOR', nil)
```
Comment (DavidS) [inline lib/rspec-puppet/support.rb]: Seeing those values hardcoded here makes me very itchy. Please add a set of tests to verify the underlying ruby platform like this:

```
# make sure we do not miss changes in the ruby platform relevant for lib/rspec-puppet/support.rb stub_file_consts
describe "consts on windows", :if => RSpec::Support::OS.windows? do
  it { expect(File.PATH_SEPARATOR).to eq(':') }
  it { expect(File.ALT_SEPARATOR).to be_nil }
end

describe "consts on linux", :unless => RSpec::Support::OS.windows? do
  it { expect(File.PATH_SEPARATOR).to eq(';') }
  it { expect(File.ALT_SEPARATOR).to eq("\\") }
end
```

File: lib/rspec-puppet/support.rb [hunk 4]
```diff
@@ -254,6 +275,12 @@ def build_catalog_without_cache(nodename, facts_val, trusted_facts_val, hiera_co
     end
 
     def stub_facts!(facts)
+      if facts['operatingsystem'] && facts['operatingsystem'].to_s.downcase == 'windows'
+        Puppet::Util::Platform.pretend_to_be :windows
+      else
+        Puppet::Util::Platform.pretend_to_be :linux
+      end
+      Puppet.settings[:autosign] = false
```
Comment (DavidS) [inline lib/rspec-puppet/support.rb]: Preserve the note on Windows validating the value here, and note that the setting is not used during unit-testing anyways.

File: lib/rspec-puppet/monkey_patches.rb [hunk 5]
```diff
@@ -0,0 +1,90 @@
...
+  end
+end
+
+# Prevent Puppet from requiring 'puppet/util/windows' if we're pretending to be
+# windows, otherwise it will require other libraries that probably won't be
+# available on non-windows hosts.
+module Kernel
+  alias :old_require :require
+  def require(path)
+    return if path == 'puppet/util/windows' && Puppet::Util::Platform.pretend_windows?
```
Comment (DavidS) [inline lib/rspec-puppet/monkey_patches.rb]: Will this be confusing/dangerous to people? Do we have a (easy) way to emit a single debug/warning message when this happens?

File: lib/rspec-puppet/support.rb (hunk 3 above)
Comment (rodjek) [inline lib/rspec-puppet/support.rb]: Yeah, it's a nasty solution for a nasty problem (Puppet really doesn't want to do what we're forcing it to do) 😀

**Comment by james-stocks** [comment]
I've made a rough attempt to run these changes past appveyor (rough as in the appveyor config might not be totally correct and appropriate yet) and am seeing 7 failures: https://ci.appveyor.com/project/rodjek/rspec-puppet/build/1.0.12/job/f7rgrritnbw4y2i8

```
rspec ./spec/classes/relationship__before_spec.rb:22 # relationships::before should contain File[/tmp/foo] that comes before File[/tmp/foo/bar]
rspec ./spec/classes/relationship__before_spec.rb:23 # relationships::before should contain File[/tmp/foo/bar] that requires File[/tmp/foo]
rspec ./spec/classes/relationship__before_spec.rb:25 # relationships::before should contain Notify[bazz] that comes before File[/tmp/foo/bar]
rspec ./spec/classes/relationship__before_spec.rb:26 # relationships::before should contain Notify[qux] that requires File[/tmp/foo]
rspec ./spec/classes/relationship__before_spec.rb:27 # relationships::before should contain Notify[bazz] that comes before Notify[qux]
rspec ./spec/classes/relationship__before_spec.rb:28 # relationships::before should contain Notify[qux] that requires Notify[bazz]
rspec ./spec/classes/test_duplicate_alias_spec.rb:4 # test::duplicate_alias should compile into a catalogue without dependency cycles
```

**Comment by rodjek** [comment]
OK, I think this is finally ready to go. rspec-puppet's tests now pass (at least on my windows 10 vm) which should unblock #505.

On my linux workstation, I can run tests for windows modules (puppetlabs-wsus_client, puppetlabs-acl, puppetlabs-chocolatey were used for testing). On my windows 10 vm, I can run tests for linux modules (puppetlabs-ntp, puppetlabs-apt, puppetlabs-apache, puppetlabs-puppetdb were used for testing).

This is very much "best effort" support due to Puppet not being designed to do what we're trying to make it do (particularly in the case of compiling catalogues for non-Windows agents on Windows). All the core types should work fine, but 3rd party types might still have issues.

**Comment by Iristyle** [comment]
In particular https://github.com/puppetlabs/puppetlabs-acl/blob/master/spec/unit/type/acl_spec.rb#L277-L279 is now broken as a result of the monkey patches to Puppets file type.  There may be more fallout.

I'd suggest rethinking that change.

**Comment by DavidS** [comment]
Hi @Iristyle,

I created a ticket for you tracking this.

Cheers, David

**Comment by cdenneen** [comment]
@rodjek @DavidS looks like this is broken in 2.7.0
reverted back to 2.6.15 and working again.

**Comment by rodjek** [comment]
@cdenneen can you send me a simple example module that shows what's broken?

**Comment by franknarf8** [comment]
I seem to have an exec that fails because of the `creates` argument
Running the code on Windows; for MacOS.
Complains with : `error during compilation: Parameter creates failed on Exec[installs something]: creates must be a fully qualified path`
 ```
exec { "installs something":
    command     => "whatever",
    path        => '/usr/local/bin:/usr/bin:/bin',
    environment => ["HOME=/Users/myuser"],
    user        => 'myuser',
    creates     => "/Users/myuser/some/further/path"
}
```

**Comment by rodjek** [comment]
@franknarf8 Can you open a new issue for this please and include the contents of the spec file as well (these sort of issues are often caused by not setting the correct facts in the tests)

**Comment by cdenneen** [comment]
Using 2.7.5

```
  1) profile::webfeeds should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile }
       error during compilation: Parameter path failed on File[c:\temp]: File paths must be fully qualified, not 'c:\temp' (file: /Users/cdenneen/src/gitlab/keystone-puppet/spec/fixtures/modules/staging/manifests/init.pp, line: 26)
```

This is set in the profile::webfeeds as:

```
class profile::webfeeds(
  $temp                          = 'c:\\temp',
```

So the `\\` doesn't seem to fix it here.

@rodjek @DavidS

**Comment by uberjew666** [comment]
I'm also getting error:
`./spec/classes/profile/os/directories_spec.rb:27: error during compilation: Parameter path failed on File[C:/Scripts/]: File paths must be fully qualified, not 'C:/Scripts'`

Not sure which version, I'm using PDK 1.10
